%include "colon.inc"
colon "hello", third
db "Hello world!", 0

colon "2", second
db "this is 2", 0

colon "йцукен", qwerty1234567890
db "qwertyasdfghqwert1234567890- wertyuio_!", 0

colon "frfr", ert
db "ert", 0

colon "cat", cat
db "meow", 0

colon "cat", wrongcat
db "bark", 0

colon "cat2", cat2
db "meow2", 0

colon "dog", dog
db "meow", 0

colon "dog2", dog2
db "meow2", 0

colon "My name is Harry Potter", first
db "Hello, Harry Potter. My name is Tom Riddle.", 0
